### ISSUE TITLE
when I run in raspeberry pi,there is nothing show in calibrate screen.just a white board

### ISSUE THREAD

**Issue by youxiaojie** [andreasb242/TouchCalibrate#1]
when I run in raspberry pi,there is nothing show in calibrate screen.just a white board
show the errors:
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

**Comment by youxiaojie** [comment]
ok after install 
sudo apt-get install python3-gi-cairo

**Comment by andreasb242** [comment]
But nice to hear, somebody is using it!
